### ISSUE TITLE
Error creating package-only deployment with AWS Lambda .NET Core Deployment task

### ISSUE THREAD

**Issue by jpenniman** [aws/aws-vsts-tools#107]
We're getting an error when trying to package a dotnet core lamda function with the AWS Lambda .NET Core Deployment build/release task.

The error:
Unknown error executing docker push to Amazon Elastic Container Registry: Access to the path 'D:\a\1\a' is denied.

Here's the log:
2018-09-24T16:06:57.8106201Z ##[section]Starting: Build and Create Deployment Package
2018-09-24T16:06:57.8136538Z ==============================================================================
2018-09-24T16:06:57.8136807Z Task         : AWS Lambda .NET Core Deployment
2018-09-24T16:06:57.8138053Z Description  : Builds, packages and deploys a .NET Core AWS Lambda function or serverless application.  Optionally the task can create the deployment package for subsequent deployment in another build or release pipeline
2018-09-24T16:06:57.8138371Z Version      : 1.1.5
2018-09-24T16:06:57.8138572Z Author       : Amazon Web Services
2018-09-24T16:06:57.8139533Z Help         : Please refer to [AWS Lambda Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/) for more information on working with AWS Lambda.

More information on this task can be found in the [task reference](https://docs.aws.amazon.com/vsts/latest/userguide/lambda-netcore-deploy.html).

####Task Permissions
This task requires permissions to call the following AWS service APIs (depending on selected task options, not all APIs may be used):
* lambda:CreateFunction
* lamda:UpdateFunctionCode
* lambda:GetFunctionConfiguration
* cloudformation:CreateChangeSet
* cloudformation:ExecuteChangeSet
* cloudformation:DescribeStackEvents
* cloudformation:DeleteStack
* cloudformation:DescribeChangeSet
* cloudformation:DescribeStacks
* s3:CreateBucket
* s3:GetBucketLocation

The task also requires permissions to upload your Lambda function or serverless application content to the specified Amazon S3 bucket. Depending on the size of the application bundle, either putObject or the S3 multi-part upload APIs may be used.
2018-09-24T16:06:57.8140512Z ==============================================================================
2018-09-24T16:06:58.2541405Z Processing Lambda project at D:\a\1\s\src\ClientNotification.LookupClient
2018-09-24T16:06:58.2542050Z Reading existing aws-lambda-tools-defaults.json
2018-09-24T16:06:58.2544031Z Clearing out profile default so task credentials will be used.
2018-09-24T16:06:58.2552249Z Configuring credentials for task
2018-09-24T16:06:58.2559200Z 9c9eb004-8b30-437c-89b9-1c2cba6f907b exists true
2018-09-24T16:06:58.2560109Z ...configuring AWS credentials from service endpoint '9c9eb004-8b30-437c-89b9-1c2cba6f907b'
2018-09-24T16:06:58.2560522Z ...endpoint defines standard access/secret key credentials
2018-09-24T16:06:58.2582548Z Configuring region for task
2018-09-24T16:06:58.2584640Z ...configured to use region us-east-1, defined in task.
2018-09-24T16:06:58.2589351Z Beginning dotnet restore
2018-09-24T16:06:58.2642556Z Path to tool: C:\Program Files\dotnet\dotnet.exe
2018-09-24T16:06:58.2690285Z [command]"C:\Program Files\dotnet\dotnet.exe" restore
2018-09-24T16:06:59.1997307Z   Restoring packages for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj...
2018-09-24T16:06:59.1998466Z   Restoring packages for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj...
2018-09-24T16:07:01.6459118Z   Installing System.Net.WebHeaderCollection 4.0.1.
2018-09-24T16:07:01.6674452Z   Installing System.Net.Requests 4.0.11.
2018-09-24T16:07:01.7656821Z   Installing AWSSDK.Core 3.3.25.3.
2018-09-24T16:07:01.7667587Z   Installing AWSSDK.Core 3.3.22.1.
2018-09-24T16:07:01.7880950Z   Installing AWSSDK.SecurityToken 3.3.4.3.
2018-09-24T16:07:01.8230782Z   Installing AWSSDK.DynamoDBv2 3.3.14.2.
2018-09-24T16:07:01.8271843Z   Installing AWSSDK.S3 3.3.18.2.
2018-09-24T16:07:01.8459145Z   Installing Amazon.Lambda.Serialization.Json 1.3.0.
2018-09-24T16:07:01.8461315Z   Installing AWSSDK.IdentityManagement 3.3.6.3.
2018-09-24T16:07:01.8808968Z   Installing Amazon.Lambda.Core 1.0.0.
2018-09-24T16:07:01.8975461Z   Installing AWSSDK.Lambda 3.3.13.2.
2018-09-24T16:07:02.2071052Z   Installing AWSSDK.CloudFormation 3.3.10.2.
2018-09-24T16:07:02.2073871Z   Installing YamlDotNet.Signed 4.2.1.
2018-09-24T16:07:02.2239590Z   Installing Amazon.Lambda.Tools 2.1.3.
2018-09-24T16:07:27.7093759Z   Generating MSBuild file D:\a\1\s\src\ClientNotification.LookupClient\obj\ClientNotification.LookupClient.csproj.nuget.g.props.
2018-09-24T16:07:27.7116984Z   Generating MSBuild file D:\a\1\s\src\ClientNotification.LookupClient\obj\ClientNotification.LookupClient.csproj.nuget.g.targets.
2018-09-24T16:07:27.7471833Z   Restore completed in 28.55 sec for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj.
2018-09-24T16:07:27.7922723Z   Restore completed in 28.52 sec for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj.
2018-09-24T16:07:27.8498806Z Beginning Lambda Deployment
2018-09-24T16:07:27.8500604Z Performing package-only build of function, output package will be placed in D:\a\1\a
2018-09-24T16:07:27.8551214Z Path to tool: C:\Program Files\dotnet\dotnet.exe
2018-09-24T16:07:27.8574990Z [command]"C:\Program Files\dotnet\dotnet.exe" lambda package -o D:\a\1\a --region us-east-1 -fn ClientNotification-v2-LookupClient -fh ClientNotification.LookupClient::ClientNotification.LookupClient.Function::FunctionHandler --function-memory-size 128 --function-timeout 30 --disable-interactive true
2018-09-24T16:07:37.4484767Z Amazon Lambda Tools for .NET Core applications (2.1.3)
2018-09-24T16:07:37.4486128Z Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
2018-09-24T16:07:37.4486562Z 	
2018-09-24T16:07:40.0008147Z Executing publish command
2018-09-24T16:07:40.1322273Z ... invoking 'dotnet publish', working folder 'D:\a\1\s\src\ClientNotification.LookupClient\bin\Release\netcoreapp2.0\publish'
2018-09-24T16:07:40.4329564Z ... publish: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
2018-09-24T16:07:40.4330265Z ... publish: Copyright (C) Microsoft Corporation. All rights reserved.
2018-09-24T16:07:41.0967642Z ... publish:   Restoring packages for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj...
2018-09-24T16:07:41.0968919Z ... publish:   Restore completed in 46.16 ms for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj.
2018-09-24T16:07:49.4192749Z ... publish:   Installing System.Security.Claims 4.0.1.
2018-09-24T16:07:49.5373685Z ... publish:   Installing System.Security.Principal.Windows 4.0.0.
2018-09-24T16:07:49.7123649Z ... publish:   Installing System.Net.NameResolution 4.0.0.
2018-09-24T16:07:49.9704463Z ... publish:   Installing runtime.unix.System.Private.Uri 4.0.1.
2018-09-24T16:07:50.1513527Z ... publish:   Installing runtime.linux-x64.Microsoft.NETCore.DotNetAppHost 2.0.0.
2018-09-24T16:07:50.1999707Z ... publish:   Installing runtime.unix.System.Net.Sockets 4.1.0.
2018-09-24T16:07:50.6304314Z ... publish:   Installing runtime.any.System.Threading.Timer 4.0.1.
2018-09-24T16:07:50.6305379Z ... publish:   Installing runtime.any.System.Runtime.InteropServices 4.1.0.
2018-09-24T16:07:50.6308473Z ... publish:   Installing runtime.any.System.Runtime.Handles 4.0.1.
2018-09-24T16:07:50.6309982Z ... publish:   Installing runtime.linux-x64.Microsoft.NETCore.App 2.0.0.
2018-09-24T16:07:50.6310279Z ... publish:   Installing runtime.unix.System.Net.Primitives 4.0.11.
2018-09-24T16:07:50.6310946Z ... publish:   Installing runtime.linux-x64.Microsoft.NETCore.DotNetHostPolicy 2.0.0.
2018-09-24T16:07:50.6311244Z ... publish:   Installing runtime.unix.System.IO.FileSystem 4.0.1.
2018-09-24T16:07:51.0718095Z ... publish:   Installing runtime.any.System.Globalization.Calendars 4.0.1.
2018-09-24T16:07:51.0720006Z ... publish:   Installing runtime.any.System.Diagnostics.Tracing 4.1.0.
2018-09-24T16:07:51.0723998Z ... publish:   Installing runtime.any.System.Diagnostics.Tools 4.0.1.
2018-09-24T16:07:51.0725753Z ... publish:   Installing runtime.unix.Microsoft.Win32.Primitives 4.0.1.
2018-09-24T16:07:51.0726902Z ... publish:   Installing runtime.any.System.Reflection.Primitives 4.0.1.
2018-09-24T16:07:51.0727755Z ... publish:   Installing runtime.any.System.IO 4.1.0.
2018-09-24T16:07:54.0221357Z ... publish:   Installing runtime.any.System.Runtime 4.1.0.
2018-09-24T16:07:54.0223287Z ... publish:   Installing runtime.unix.System.Console 4.0.0.
2018-09-24T16:07:54.0235885Z ... publish:   Installing runtime.any.System.Reflection 4.1.0.
2018-09-24T16:07:54.0238818Z ... publish:   Installing runtime.linux-x64.Microsoft.NETCore.DotNetHostResolver 2.0.0.
2018-09-24T16:07:54.0241770Z ... publish:   Installing System.Private.Uri 4.0.1.
2018-09-24T16:07:54.0246575Z ... publish:   Installing runtime.any.System.Threading.Tasks 4.0.11.
2018-09-24T16:07:54.0256610Z ... publish:   Installing runtime.any.System.Text.Encoding 4.0.11.
2018-09-24T16:07:54.0263247Z ... publish:   Installing runtime.any.System.Text.Encoding.Extensions 4.0.11.
2018-09-24T16:07:54.0269770Z ... publish:   Installing runtime.any.System.Collections 4.0.11.
2018-09-24T16:07:54.0271210Z ... publish:   Installing runtime.unix.System.Diagnostics.Debug 4.0.11.
2018-09-24T16:07:54.0273576Z ... publish:   Installing runtime.any.System.Globalization 4.0.11.
2018-09-24T16:07:54.0279820Z ... publish:   Installing runtime.any.System.Reflection.Extensions 4.0.1.
2018-09-24T16:07:54.6331605Z ... publish:   Installing runtime.any.System.Resources.ResourceManager 4.0.1.
2018-09-24T16:07:54.6332267Z ... publish:   Installing runtime.unix.System.Runtime.Extensions 4.1.0.
2018-09-24T16:08:01.3192490Z ... publish:   Restore completed in 20.2 sec for D:\a\1\s\src\ClientNotification.LookupClient\ClientNotification.LookupClient.csproj.
2018-09-24T16:08:06.2471458Z ... publish:   ClientNotification.LookupClient -> D:\a\1\s\src\ClientNotification.LookupClient\bin\Release\netcoreapp2.0\linux-x64\ClientNotification.LookupClient.dll
2018-09-24T16:08:07.3555512Z ... publish:   ClientNotification.LookupClient -> D:\a\1\s\src\ClientNotification.LookupClient\bin\Release\netcoreapp2.0\publish\
2018-09-24T16:08:07.4033490Z Zipping publish folder D:\a\1\s\src\ClientNotification.LookupClient\bin\Release\netcoreapp2.0\publish to D:\a\1\a
2018-09-24T16:08:07.5359939Z Unknown error executing docker push to Amazon Elastic Container Registry: Access to the path 'D:\a\1\a' is denied.
2018-09-24T16:08:09.2000066Z    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
2018-09-24T16:08:09.2000939Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2018-09-24T16:08:09.2001596Z    at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
2018-09-24T16:08:09.2002069Z    at Amazon.Lambda.Tools.LambdaPackager.BundleWithDotNetCompression(String zipArchivePath, String publishLocation, Boolean flattenRuntime, IToolLogger logger)
2018-09-24T16:08:09.2003296Z    at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, Boolean disableVersionCheck, String& publishLocation, String& zipArchivePath)
2018-09-24T16:08:09.2005896Z    at Amazon.Lambda.Tools.Commands.PackageCommand.<PerformActionAsync>b__30_0()
2018-09-24T16:08:09.2006289Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2018-09-24T16:08:09.2006671Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-09-24T16:08:09.2007093Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-09-24T16:08:09.2007423Z --- End of stack trace from previous location where exception was thrown ---
2018-09-24T16:08:09.2007712Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-09-24T16:08:09.2008028Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-24T16:08:09.2008347Z    at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.<ExecuteAsync>d__10.MoveNext()
2018-09-24T16:08:09.2266495Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 4294967295
2018-09-24T16:08:09.2293667Z ##[section]Finishing: Build and Create Deployment Package

Our configuration:
![image](https://user-images.githubusercontent.com/3700572/45964365-96a2a600-bff3-11e8-80fa-84b579d8b926.png)

Other tasks supplied by Microsoft and other third parties are able to write to the Build.ArtifactStagingDirectory without an issue.

**Comment by jpenniman** [comment]
I found my issue. The output needs to be a actual file name, not just a path.
