### ISSUE TITLE
Cannot update CloudFormation stack due to 'Resource is not in the state stackUpdateComplete'

### ISSUE THREAD

**Issue by karl-barbour** [aws/aws-vsts-tools#151]
I am using https://docs.aws.amazon.com/vsts/latest/userguide/cloudformation-create-update.html via Azure DevOps and have encountered what I believe to be a bug.

I deployed a stack update which failed and resulted in rollback in CloudFormation. It is now in state 'UPDATE_ROLLBACK_COMPLETE'.

When I try to update the stack again (now I've corrected the issue), the Azure DevOps task gives me the following:

```2019-04-20T20:18:16.4710467Z ##[section]Starting: Create/Update Stack
2019-04-20T20:18:16.4829101Z ==============================================================================
2019-04-20T20:18:16.4829228Z Task         : AWS CloudFormation Create/Update Stack
2019-04-20T20:18:16.4829316Z Description  : Creates a new AWS CloudFormation stack or updates the stack if it exists.
2019-04-20T20:18:16.4829406Z Version      : 1.1.8
2019-04-20T20:18:16.4829470Z Author       : Amazon Web Services
2019-04-20T20:18:16.4829713Z Help         : Please refer to [AWS CloudFormation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/) for more details on working with AWS CloudFormation.

More information on this task can be found in the [task reference](https://docs.aws.amazon.com/vsts/latest/userguide/cloudformation-create-update.html).

####Task Permissions
This task requires permissions to call the following AWS service APIs (depending on selected task options, not all APIs may be used):
* cloudformation:CreateChangeSet
* cloudformation:CreateStack
* cloudformation:DeleteChangeSet
* cloudformation:DescribeChangeSet
* cloudformation:DescribeStacks
* cloudformation:DescribeStackResources
* cloudformation:ExecuteChangeSet
* cloudformation:UpdateStack

The task may also require permissions to upload your application template to the specified Amazon S3 bucket.
2019-04-20T20:18:16.4830034Z ==============================================================================
2019-04-20T20:18:16.9177208Z Configuring credentials for task
2019-04-20T20:18:16.9197593Z 2eb856e4-a89c-47b7-afad-eaa49e607a96 exists true
2019-04-20T20:18:16.9197857Z ...configuring AWS credentials from service endpoint '2eb856e4-a89c-47b7-afad-eaa49e607a96'
2019-04-20T20:18:16.9197955Z ...endpoint defines standard access/secret key credentials
2019-04-20T20:18:16.9227411Z Configuring region for task
2019-04-20T20:18:16.9229085Z ...configured to use region us-east-1, defined in task.
2019-04-20T20:18:16.9334801Z Configuring credentials for task
2019-04-20T20:18:16.9337939Z 2eb856e4-a89c-47b7-afad-eaa49e607a96 exists true
2019-04-20T20:18:16.9338916Z ...configuring AWS credentials from service endpoint '2eb856e4-a89c-47b7-afad-eaa49e607a96'
2019-04-20T20:18:16.9339432Z ...endpoint defines standard access/secret key credentials
2019-04-20T20:18:16.9341205Z Configuring region for task
2019-04-20T20:18:16.9342713Z ...configured to use region us-east-1, defined in task.
2019-04-20T20:18:16.9440025Z Checking existence for stack XXX
2019-04-20T20:18:17.4240263Z Stack exists, switching to update stack mode
2019-04-20T20:18:17.4244798Z Updating stack with template file XXX
2019-04-20T20:18:17.4246877Z Loading template file from XXX
2019-04-20T20:18:17.4253193Z Loading template parameters file XXX
2019-04-20T20:18:17.4256974Z Successfully loaded template parameters
2019-04-20T20:18:17.4258527Z Setting capability CAPABILITY_IAM for stack
2019-04-20T20:18:17.4259006Z Setting capability CAPABILITY_NAMED_IAM for stack
2019-04-20T20:18:18.1793457Z Waiting for stack XXX to reach update complete status
2019-04-20T20:18:49.0160001Z Stack update request failed with error: 'Stack XXX failed to reach update completion status, error: 'Resource is not in the state stackUpdateComplete'' Error: Stack XXX failed to reach update completion status, error: 'Resource is not in the state stackUpdateComplete'
2019-04-20T20:18:49.0160750Z     at .<anonymous> (D:\a\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.1.8\CloudFormationCreateOrUpdateStack.js:9:23747)
2019-04-20T20:18:49.0161387Z     at throw (native)
2019-04-20T20:18:49.0162300Z     at o (D:\a\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.1.8\CloudFormationCreateOrUpdateStack.js:9:12943)
2019-04-20T20:18:49.0165389Z     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2019-04-20T20:18:49.0166299Z ##[error]Error: Stack XXX failed to reach update completion status, error: 'Resource is not in the state stackUpdateComplete'
2019-04-20T20:18:49.0237892Z ##[section]Finishing: Create/Update Stack
```

I am then blocked from continuing as it thinks the stack is in a bad state, when realistically it is not. I can work around by applying a manual update or manually deleting the stack and allowing the pipeline to recreate it, but in an automated CI/CD pipeline this isn't ideal. 

I understand the thought behind this state check, but either we need to add an option to ignore stacks in a rollback state or add this state to the whitelist.

Thoughts?

**Comment by karl-barbour** [comment]
Hmm actually this is the error displayed when the update fails, not when it tries to re-deploy. I misread. 

No issue found.

**Comment by ankittyagi20** [comment]
@karl-barbour so what was the cause of the above error, and how did you resolve it?

**Comment by rasao** [comment]
@karl-barbour pls can u help me on this.. I am getting the same error while deploying the cloud formation template from azure devops. pls help

**Comment by karl-barbour** [comment]
Hi @ankittyagi20 sorry, I didn't see this until now! I didn't find an issue or resolve it, was user error - this is the message given when the update itself fails,I believe it is intended behaviour.

@rasao as above :)
