### ISSUE TITLE
AWS Beanstalk Deployment task during Release fails on Hosted agent

### ISSUE THREAD

**Issue by ahc2483** [aws/aws-vsts-tools#16]
When running the AWS Beanstalk Deployment task on a Hosted agent, the task fails every time with the following error:

**##[error]System.IO.FileNotFoundException: The specified module 'AWSPowerShell' was not loaded because no valid module file was found in any module directory.**

Full logs of recent run below (AWS credentials removed from log):

2017-09-11T15:25:57.2848220Z ##[section]Starting: Release new version to Test
2017-09-11T15:25:57.2848220Z ==============================================================================
2017-09-11T15:25:57.2848220Z Task         : AWS Beanstalk Deployment
2017-09-11T15:25:57.2848220Z Description  : Build task to upload a new application version to an Elastic Beanstalk in AWS.
2017-09-11T15:25:57.2848220Z Version      : 1.0.0
2017-09-11T15:25:57.2848220Z Author       : Mark Buggermann
2017-09-11T15:25:57.2848220Z Help         : [More Information](https://marketplace.visualstudio.com/items?spirit21.AwsBeanstalkReleaseExtension)
2017-09-11T15:25:57.2848220Z ==============================================================================
2017-09-11T15:25:57.2928210Z Preparing task execution handler.
2017-09-11T15:26:01.2627616Z Executing the powershell script: d:\a\_tasks\AwsBeanstalkRelease_506e537c-a122-40ae-928d-13e78628f6ff\1.0.0\beanstalk_deployment.ps1
2017-09-11T15:26:01.5377618Z Loading PowerShell module for AWS
2017-09-11T15:26:01.5777403Z ##[error]System.IO.FileNotFoundException: The specified module 'AWSPowerShell' was not loaded because no valid module file was found in any module directory.
2017-09-11T15:26:01.5797394Z AccessKey:
2017-09-11T15:26:01.5797394Z 
2017-09-11T15:26:01.5797394Z 
2017-09-11T15:26:01.5807415Z SecretKey:
2017-09-11T15:26:01.5807415Z 
2017-09-11T15:26:01.5807415Z 
2017-09-11T15:26:01.5807415Z Version: 12
2017-09-11T15:26:01.5807415Z 
2017-09-11T15:26:01.5807415Z 
2017-09-11T15:26:01.5807415Z Region: us-east-1
2017-09-11T15:26:01.5807415Z 
2017-09-11T15:26:01.5807415Z 
2017-09-11T15:26:01.5817398Z Setting aws credentials
2017-09-11T15:26:01.5817398Z 
2017-09-11T15:26:01.5817398Z 
2017-09-11T15:26:05.5383829Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: System.Management.Automation.CommandNotFoundException: The term 'Set-AwsCredentials' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2017-09-11T15:26:05.5383829Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-09-11T15:26:05.5383829Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-09-11T15:26:05.5383829Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-09-11T15:26:05.5383829Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-09-11T15:26:05.5532898Z ##[error]PowerShell script completed with 2 errors.
2017-09-11T15:26:05.5542913Z ##[section]Finishing: Release new version to Test

**Comment by normj** [comment]
Looks like you are using the AWS Beanstalk Deployment extension by Spirit21 which is not maintained by AWS. https://marketplace.visualstudio.com/items?itemName=spirit21.AwsBeanstalkReleaseExtension

The AWS owned and maintained extensions can be found here: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-vsts-tools

**Comment by ahc2483** [comment]
@normj Oh jeez. You are absolutely right - apparently I had installed both and was choosing the wrong task when configuring my release. Will give the official AWS version a go. I am deploying a PHP site and will try the "Web Deploy Archive" option and see if that will work.
