### ISSUE TITLE
S3 Upload XMLParserError

### ISSUE THREAD

**Issue by DevOpUser** [aws/aws-vsts-tools#25]
Trying to upload files into a new S3 bucket the build using the S3Upload task fails with the following error (here full log related to the task):

2017-10-04T15:22:47.0249089Z ##[debug]Evaluating condition for step: 'S3 Upload: BasicTemplate'
2017-10-04T15:22:47.0249089Z ##[debug]Evaluating: succeeded()
2017-10-04T15:22:47.0249089Z ##[debug]Evaluating succeeded:
2017-10-04T15:22:47.0249089Z ##[debug]=> (Boolean) True
2017-10-04T15:22:47.0249089Z ##[debug]Expanded: True
2017-10-04T15:22:47.0249089Z ##[debug]Result: True
2017-10-04T15:22:47.0249089Z ##[section]Starting: S3 Upload: BasicTemplate
2017-10-04T15:22:47.0405355Z ==============================================================================
2017-10-04T15:22:47.0405355Z Task         : AWS S3 Upload
2017-10-04T15:22:47.0405355Z Description  : Upload file and folder content to an Amazon Simple Storage Service (S3) Bucket
2017-10-04T15:22:47.0405355Z Version      : 1.0.7
2017-10-04T15:22:47.0405355Z Author       : Amazon Web Services
2017-10-04T15:22:47.0405355Z Help         : Please refer to [Working with Amazon S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) for more information on working with Amazon S3.
2017-10-04T15:22:47.0405355Z ==============================================================================
2017-10-04T15:22:47.3217918Z ##[debug]agent.TempDirectory=T:\AWS_AgtBld001\_work\_temp
2017-10-04T15:22:47.3217918Z ##[debug]loading inputs and endpoints
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_$/
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_****************************
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_********************************_PASSWORD
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_********************************_USERNAME
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_SCHEME_$/
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_SCHEME_***************************************
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2017-10-04T15:22:47.3217918Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2017-10-04T15:22:47.3217918Z ##[debug]loading INPUT_AWSCREDENTIALS
2017-10-04T15:22:47.3217918Z ##[debug]loading INPUT_BUCKETNAME
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_CREATEBUCKET
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_FILESACL
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_FLATTENFOLDERS
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_GLOBEXPRESSIONS
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_OVERWRITE
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_REGIONNAME
2017-10-04T15:22:47.3374175Z ##[debug]loading INPUT_SOURCEFOLDER
2017-10-04T15:22:47.3374175Z ##[debug]loaded 19
2017-10-04T15:22:47.3374175Z ##[debug]Agent.ProxyUrl=undefined
2017-10-04T15:22:47.3374175Z ##[debug]Agent.CAInfo=undefined
2017-10-04T15:22:47.3374175Z ##[debug]Agent.ClientCert=undefined
2017-10-04T15:22:47.3686684Z ##[debug]check path : T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\task.json
2017-10-04T15:22:47.3686684Z ##[debug]set resource file to: T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\task.json
2017-10-04T15:22:47.3686684Z ##[debug]system.culture=en-US
2017-10-04T15:22:47.3686684Z ##[debug]awsCredentials=*****************************
2017-10-04T15:22:47.3842932Z *************************** exists true
2017-10-04T15:22:47.3842932Z ##[debug]***************************** exists true
2017-10-04T15:22:47.3842932Z ##[debug]regionName=eu-west-1
2017-10-04T15:22:47.3842932Z ##[debug]bucketName=BasicTemplate
2017-10-04T15:22:47.3842932Z ##[debug]overwrite=true
2017-10-04T15:22:47.3842932Z ##[debug]flattenFolders=false
2017-10-04T15:22:47.3842932Z ##[debug]sourceFolder=T:\AWS_AgtBld001\_work\5\s
2017-10-04T15:22:47.3842932Z ##[debug]check path : T:\AWS_AgtBld001\_work\5\s
2017-10-04T15:22:47.3842932Z ##[debug]targetFolder=null
2017-10-04T15:22:47.3842932Z ##[debug]globExpressions=**
2017-10-04T15:22:47.3842932Z ##[debug]filesAcl=public-read-write
2017-10-04T15:22:47.3842932Z ##[debug]createBucket=true
2017-10-04T15:22:47.3842932Z ##[debug]contentType=null
2017-10-04T15:22:47.4467990Z Bucket BasicTemplate does not appear to exist (or you do not have access). Attempting to create in region eu-west-1.
2017-10-04T15:22:47.7347845Z Failed to create bucket { XMLParserError: Unexpected close tag
2017-10-04T15:22:47.7347845Z Line: 6
2017-10-04T15:22:47.7347845Z Column: 7
2017-10-04T15:22:47.7347845Z Char: >
2017-10-04T15:22:47.7347845Z     at error (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:22047:10)
2017-10-04T15:22:47.7347845Z     at strictFail (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:22073:7)
2017-10-04T15:22:47.7347845Z     at closeTag (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:22267:9)
2017-10-04T15:22:47.7347845Z     at Object.write (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:22829:13)
2017-10-04T15:22:47.7347845Z     at Parser.exports.Parser.Parser.parseString (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:10388:31)
2017-10-04T15:22:47.7347845Z     at Parser.parseString (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:9887:59)
2017-10-04T15:22:47.7347845Z     at NodeXmlParser.parse (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:21245:10)
2017-10-04T15:22:47.7347845Z     at Request.extractError (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:24616:39)
2017-10-04T15:22:47.7347845Z     at Request.callListeners (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:9476:20)
2017-10-04T15:22:47.7347845Z     at Request.emit (T:\AWS_AgtBld001\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.7\S3Upload.js:9448:10)
2017-10-04T15:22:47.7347845Z   message: 'Unexpected close tag\nLine: 6\nColumn: 7\nChar: >',
2017-10-04T15:22:47.7347845Z   code: 'XMLParserError',
2017-10-04T15:22:47.7347845Z   retryable: true,
2017-10-04T15:22:47.7347845Z   time: 2017-10-04T15:22:47.734Z,
2017-10-04T15:22:47.7347845Z   statusCode: 400 }
2017-10-04T15:22:47.7347845Z ##[debug]task result: Failed
2017-10-04T15:22:47.7504026Z ##[error]XMLParserError: Unexpected close tag
Line: 6
Column: 7
Char: >
2017-10-04T15:22:47.7504026Z ##[debug]Processed: ##vso[task.issue type=error;]XMLParserError: Unexpected close tag%0ALine: 6%0AColumn: 7%0AChar: >
2017-10-04T15:22:47.7504026Z ##[debug]Processed: ##vso[task.complete result=Failed;]XMLParserError: Unexpected close tag%0ALine: 6%0AColumn: 7%0AChar: >
2017-10-04T15:22:47.7504026Z ##[section]Finishing: S3 Upload: BasicTemplate

**Comment by steveataws** [comment]
It doesn't yet explain the xml parse error, for which I'll need to follow up with our AWS Node.js sdk team for ideas, but I wanted to check - does the account you are using have permissions to create buckets? And did the bucket really not exist at the time the task was run (ie we didn't get a false report from the bucket existence test).

If you pre-create the bucket, does the task then work?

**Comment by DevOpUser** [comment]
The IAM user used to generate access key and secret access key insert into the enpoint which the build was running with has Administrator permissions; the following is the policy attached:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
Therefore the user shuold be able to execute any action on all resources, S3 buckets included.
The error occurs if :
- the bucket really doesn't exist
- the bucket exists but the target folder within it still not
- both, bucket and target folder, already exist
I try to add some further details:
we are working behind a company proxy and since the task didn't work (even if HTTP_PROXY and HTTPS_PROXY environment variables were created on the build machine; we have seen the solution proposed into the thread related to the issue number 20 on this site but we had already found the below workaround before see that thread) we have explicitly set the proxy settings inside
the S3Upload.js file within the httpOptions object. All other AWS VSTS tasks (for example create/update stack and delete stack) we have used with this workaround work correctly, therefore the error seems not to be related to this change.
Adding some debug console log to the S3Upload.js file seems that error occurs into the function “emit” on what is contained into the the parameter eventArgs.

**Comment by DevOpUser** [comment]
errata corrige:
"Action": "*",
"Resource": "*"

**Comment by steveataws** [comment]
Thanks for the policy details, we'll give that a try. If your bucket name is DNS compatible, the underlying sdk will switch over to virtual host style addressing for the S3 endpoint and I'm wondering if that is getting tangled up with your proxy settings. As you've already modified the task code to support the proxy, it might be worth also adding in the sdk's setting to force path style addressing to see if this works better. You can do this by setting the [s3ForcePathStyle](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) property on the configuration options when the task constructs the S3 object.

Support for proxy settings is being added, along with some new diagnostic logging options so we can get the request/response trace into the task's debug logs. I don't have an ETA for release yet, but hopefully not too far distant.

**Comment by DevOpUser** [comment]
Thanks for the tip. I have tried also with the s3ForcePathStyle property forced to true but the error unfortunately still occurs.
