### ISSUE TITLE
CFN - Task fails if there are no updates to apply

### ISSUE THREAD

**Issue by r2690698** [aws/aws-vsts-tools#28]
when trying to update a stack in our deployment process it is failing because a stack that is being processed 1st dose not contain any changes. this means the lower stacks will never get updated and your release pipeline will always fail. 

for example, i have the following CFN Create /Update templates tasks, i have made a change to stack 3 and this triggers an update of the release. the process starts from stack one and fails as there is no changes for this stack. 

Run on Agent 
-----------------
CFN Stack 1  - No Change - Failed ! 
CFN Stack 2  
CFN Stack 3  - Has changes in GIT to apply ! 

Expected behavior for the release process would be check to see if there are changes, if so make the change set and apply, if not pass and continue on to the next one.

**Comment by steveataws** [comment]
The CreateOrUpdateStack task can perform the update using either a direct call to the service's UpdateStack API or by executing a change set. In both cases the task catches errors and inspects to see if it was due to a 'nothing to do' condition (which it has to do by inspecting the error message content). My guess is that in your case, the error messaging isn't getting trapped.

Can you post an example of the error message you are seeing when the update fails?

**Comment by r2690698** [comment]
Hello, 

this is the error from the build server 
```
2017-10-11T17:52:13.2253391Z Waiting for change set a004 to be validated for stack rtx-dev01-stack-eu-west-1-s3
2017-10-11T17:52:13.4080809Z Request to create change set failed with error Stack a004 failed to create successfully from the change set. Error: Resource is not in the state changeSetCreateComplete Error: Stack a004 failed to create successfully from the change set. Error: Resource is not in the state changeSetCreateComplete
2017-10-11T17:52:13.4080809Z     at Function.<anonymous> (d:\a\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.0.7\CloudFormationCreateOrUpdateStack.js:12267:23)
2017-10-11T17:52:13.4080809Z     at throw (native)
2017-10-11T17:52:13.4090817Z     at rejected (d:\a\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.0.7\CloudFormationCreateOrUpdateStack.js:11925:65)
2017-10-11T17:52:13.4090817Z     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2017-10-11T17:52:13.4090817Z ##[error]Error: Stack a004 failed to create successfully from the change set. Error: Resource is not in the state changeSetCreateComplete
```

but this is the cfn stack error from the failed change set form the UI 

Status:
FAILED - The submitted information didn't contain changes. Submit different information to create a change set.

**Comment by steveataws** [comment]
Thanks. Are all of your stack updates being done using change sets?

**Comment by r2690698** [comment]
Yup, they are, the idea is that if we make any changes to a template or param on our cicd branch we test it, deploying and exacate the change set to QA -->PreProd then Prod as a unexecuted change set ready for change control to approve.

**Comment by steveataws** [comment]
Ok, we'll work at updating the tasks so that if the updatestack or execchangeset operations fails with a 'no changes' error, we'll output a warning to the task log rather than causing the task to fail. I don't have an ETA right now, but shouldn't be too long.

**Comment by r2690698** [comment]
@steveataws brill thanks very much ! 

i have it just now to 'continue on error' so i get a 'partial success' in orrange. that option realy should not be enabled and the task sequence should still pass as 'success' in green other wise you will also be checking the logs to see if its a real error or a no changes error. 

Steve C

**Comment by steveataws** [comment]
v1.0.8 has now been released which contains updates to the CloudFormation task to detect the no-changes condition and emit a warning, rather than failing the task.

Resolving issue; feel free to reopen if you still encounter issues.

**Comment by r2690698** [comment]
@steveataws works perfectly HUGE thanks for a quick turn around !
