### ISSUE TITLE
I am not able to add session_token variable in aws connection feature of VSTS . Please help

### ISSUE THREAD

**Issue by akkipuneet** [aws/aws-vsts-tools#46]
I am getting below error . I assume it is related to my session token .

2017-12-06T14:16:02.6827252Z ##[section]Starting: S3 Upload: MyBUCKET
2017-12-06T14:16:02.6831278Z ==============================================================================
2017-12-06T14:16:02.6831563Z Task         : AWS S3 Upload
2017-12-06T14:16:02.6831955Z Description  : Upload file and folder content to an Amazon Simple Storage Service (S3) Bucket
2017-12-06T14:16:02.6832215Z Version      : 1.0.14
2017-12-06T14:16:02.6832422Z Author       : Amazon Web Services
2017-12-06T14:16:02.6832759Z Help         : Please refer to [Working with Amazon S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) for more information on working with Amazon S3.
2017-12-06T14:16:02.6833117Z ==============================================================================
2017-12-06T14:16:24.2184412Z 4b091740-92a4-44e7-99e7-ce1a7ab67bd5 exists true
2017-12-06T14:16:24.2191092Z Configuring task to use role-based credentials.
2017-12-06T14:16:25.6892711Z Bucket MyBUCKET does not appear to exist (or you do not have access). Attempting to create in region us-east-2.
2017-12-06T14:16:25.7230982Z Failed to create bucket { CredentialsError: Missing credentials in config
2017-12-06T14:16:25.7232455Z     at Request.extractError (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:5398:29)
2017-12-06T14:16:25.7232987Z     at Request.callListeners (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:7632:20)
2017-12-06T14:16:25.7234019Z     at Request.emit (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:7604:10)
2017-12-06T14:16:25.7234759Z     at Request.emit (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:14799:14)
2017-12-06T14:16:25.7235775Z     at Request.transition (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:14138:10)
2017-12-06T14:16:25.7236769Z     at AcceptorStateMachine.runTo (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:14941:12)
2017-12-06T14:16:25.7239183Z     at d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:14953:10
2017-12-06T14:16:25.7240099Z     at Request.<anonymous> (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:14154:9)
2017-12-06T14:16:25.7240997Z     at Request.<anonymous> (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:14801:12)
2017-12-06T14:16:25.7241980Z     at Request.callListeners (d:\a\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.14\S3Upload.js:7642:18)
2017-12-06T14:16:25.7242467Z   message: 'Missing credentials in config',
2017-12-06T14:16:25.7242827Z   code: 'CredentialsError',
2017-12-06T14:16:25.7243201Z   time: 2017-12-06T14:16:25.716Z,
2017-12-06T14:16:25.7243563Z   requestId: '0b5169cf-da90-11e7-b669-73e0107f4698',
2017-12-06T14:16:25.7243925Z   statusCode: 403,
2017-12-06T14:16:25.7244357Z   retryable: false,
2017-12-06T14:16:25.7244661Z   retryDelay: 93.85135920368765,
2017-12-06T14:16:25.7244965Z   originalError: 
2017-12-06T14:16:25.7245303Z    { message: 'Could not load credentials from TemporaryCredentials',
2017-12-06T14:16:25.7245687Z      code: 'CredentialsError',
2017-12-06T14:16:25.7246008Z      time: 2017-12-06T14:16:25.716Z,
2017-12-06T14:16:25.7246325Z      requestId: '0b5169cf-da90-11e7-b669-73e0107f4698',
2017-12-06T14:16:25.7246643Z      statusCode: 403,
2017-12-06T14:16:25.7246945Z      retryable: false,
2017-12-06T14:16:25.7247302Z      retryDelay: 93.85135920368765,
2017-12-06T14:16:25.7247599Z      originalError: 
2017-12-06T14:16:25.7247887Z       { message: 'The security token included in the request is invalid.',
2017-12-06T14:16:25.7248227Z         code: 'InvalidClientTokenId',
2017-12-06T14:16:25.7248706Z         time: 2017-12-06T14:16:25.716Z,
2017-12-06T14:16:25.7249126Z         requestId: '0b5169cf-da90-11e7-b669-73e0107f4698',
2017-12-06T14:16:25.7249448Z         statusCode: 403,
2017-12-06T14:16:25.7250352Z         retryable: false,
2017-12-06T14:16:25.7253517Z         retryDelay: 93.85135920368765 } } }
2017-12-06T14:16:25.7323000Z ##[error]CredentialsError: Missing credentials in config
2017-12-06T14:16:25.7480560Z ##[section]Finishing: S3 Upload: MyBUCKET

**Comment by steveataws** [comment]
We'll take a look to see if we can repro. What fields did you fill out in the credential dialog? (Don't list the values here, just the names of the fields you populated).

**Comment by akkipuneet** [comment]
![aws_connection_issue](https://user-images.githubusercontent.com/14962650/33768511-55a1563c-dc4c-11e7-9afc-4332c34b5a48.png)

Thanks for the reply Steve . Please find above snapshot to see my aws connection configuration in my task . I tried configuring the aws connection with AWS CLI task but getting below error 
----------------------------------------------------------------------------------------------
 2017-12-08T13:41:49.8300771Z ##[section]Starting: AWS CLI: s3
2017-12-08T13:41:49.8300771Z ==============================================================================
2017-12-08T13:41:49.8300771Z Task         : AWS CLI
2017-12-08T13:41:49.8300771Z Description  : Run an AWS CLI command
2017-12-08T13:41:49.8300771Z Version      : 1.0.14
2017-12-08T13:41:49.8300771Z Author       : Amazon Web Services
2017-12-08T13:41:49.8300771Z Help         : The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services. With just one tool to download and configure, you can control multiple AWS services from the command line and automate them through scripts. You must have the AWS CLI installed to use this task. See http://docs.aws.amazon.com/cli/latest/userguide/installing.html for more details.
2017-12-08T13:41:49.8300771Z ==============================================================================
2017-12-08T13:41:50.1113236Z 4b091740-92a4-44e7-99e7-ce1a7ab67bd5 exists true
2017-12-08T13:41:50.1113236Z Configuring task to use role-based credentials.
2017-12-08T13:41:50.5644336Z ##[error]**The security token included in the request is invalid.**
2017-12-08T13:41:50.5644336Z ##[section]Finishing: AWS CLI: s3

-------------------------------------------------------------------------------------------------------------------

Dont know where to give aws_session_token value . 
FYI , My access keys are valid for one hour .

**Comment by steveataws** [comment]
Just so I'm clear, you're trying to use existing temporary session credentials to then assume a role? If that's the case, the tools don't support that currently.

The access and secret key should not be temporary (since we don't know when tasks using the credentials will run, having time-limited credentials specified would be problematic). Instead, you should specify the access and secret key for an IAM user (or you could use your root credentials, but we really don't advise that). Add in the arn of the role you want the task(s) to run under when those credentials are used and the tools will automatically generate time-limited credentials, scoped to the role, when needed. You don't need to handle the session token etc.

**Comment by steveataws** [comment]
Resolving issue as I don't think there are any changes to be done here, as explained above. If there is a usage scenario where keys plus an externally-generated session token is needed and for which the tool's current use of assume role wouldn't suit, feel free to reopen and we can discuss further.
