### ISSUE TITLE
S3Upload issue when using agent running on Windows 2008 R2

### ISSUE THREAD

**Issue by jstarrin** [aws/aws-vsts-tools#9]
I receive a "SyntaxError: Invalid or unexpected token" error when i run the build agent on a Windows 2008 R2 server.  The same build definition runs fine when it is running on a Windows 2016 server.  Both are running agent version 2.117.2.  Are there any known issues when running on Windows 2008 R2?

Here is the full log output for the S3 upload task:
2017-08-24T17:37:34.5009922Z ##[section]Starting: S3 Upload
2017-08-24T17:37:34.5029926Z ==============================================================================
2017-08-24T17:37:34.5029926Z Task         : AWS S3 Upload
2017-08-24T17:37:34.5029926Z Description  : Upload file and folder content to an Amazon Simple Storage Service (S3) Bucket
2017-08-24T17:37:34.5029926Z Version      : 1.0.4
2017-08-24T17:37:34.5029926Z Author       : Amazon Web Services
2017-08-24T17:37:34.5029926Z Help         : Please refer to [Working with Amazon S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) for more information on working with Amazon S3.
2017-08-24T17:37:34.5039928Z ==============================================================================
2017-08-24T17:37:34.7790478Z C:\agent\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.4\S3Upload.js:2177
2017-08-24T17:37:34.7790478Z /**
2017-08-24T17:37:34.7790478Z ^^^
2017-08-24T17:37:34.7790478Z SyntaxError: Invalid or unexpected token
2017-08-24T17:37:34.7810482Z     at createScript (vm.js:56:10)
2017-08-24T17:37:34.7820484Z     at Object.runInThisContext (vm.js:97:10)
2017-08-24T17:37:34.7820484Z     at Module._compile (module.js:542:28)
2017-08-24T17:37:34.7820484Z     at Object.Module._extensions..js (module.js:579:10)
2017-08-24T17:37:34.7820484Z     at Module.load (module.js:487:32)
2017-08-24T17:37:34.7820484Z     at tryModuleLoad (module.js:446:12)
2017-08-24T17:37:34.7820484Z     at Function.Module._load (module.js:438:3)
2017-08-24T17:37:34.7820484Z     at Module.runMain (module.js:604:10)
2017-08-24T17:37:34.7820484Z     at run (bootstrap_node.js:390:7)
2017-08-24T17:37:34.7820484Z     at startup (bootstrap_node.js:150:9)
2017-08-24T17:37:34.7920504Z ##[error]Exit code 1 returned from process: file name 'C:\agent\externals\node\bin\node.exe', arguments '"C:\agent\_work\_tasks\S3Upload_3a219265-181c-4ed2-9a51-75a7f308f0d5\1.0.4\S3Upload.js"'.
2017-08-24T17:37:34.7970514Z ##[section]Finishing: S3 Upload

**Comment by steveataws** [comment]
We don't know of any 2008R2 specific constraints. Our testing so far has been against whatever default hosts you get, how did you set up a 2008R2 host? Does the installed version of node match the one on 2016 server?

**Comment by jstarrin** [comment]
This is a TFS 2017.2 local install with local build agents -- not VSTS.  Both Win 2008 R2 and Win 2016 build agents are running the same version 2.117.2.  The agent packages Node.js inside it, so they both have the same Node version v6.10.3.

**Comment by hunterwerlla** [comment]
Since this is nearing two years old, was filed against a very old version, and there was no further discussion, I'm closing this. 

If you have any issues with anything, please file a new issue, thanks
