### ISSUE TITLE
Cloudformation Create/Update task timeout

### ISSUE THREAD

**Issue by ansariwn** [aws/aws-vsts-tools#98]
Hi team,

I have recently come across this issue where the 'AWS Cloudformation Create/Update Stack' task fails after 60 mins, although I have set the 'timeout in minutes' to 120 mins. Any idea why?

2018-08-28T09:48:41.6588103Z ##[section]Starting: Create/Update Stack: web-532
2018-08-28T09:48:41.6597465Z ==============================================================================
2018-08-28T09:48:41.6597687Z Task         : AWS CloudFormation Create/Update Stack
2018-08-28T09:48:41.6597872Z Description  : Creates a new AWS CloudFormation stack or updates the stack if it exists.
2018-08-28T09:48:41.6598037Z Version      : 1.1.3
2018-08-28T09:48:41.6598187Z Author       : Amazon Web Services
2018-08-28T09:48:41.6598800Z Help         : Please refer to [AWS CloudFormation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/) for more details on working with AWS CloudFormation.

More information on this task can be found in the [task reference](https://docs.aws.amazon.com/vsts/latest/userguide/cloudformation-create-update.html).

####Task Permissions
This task requires permissions to call the following AWS service APIs (depending on selected task options, not all APIs may be used):
* cloudformation:CreateChangeSet
* cloudformation:CreateStack
* cloudformation:DeleteChangeSet
* cloudformation:DescribeChangeSet
* cloudformation:DescribeStacks
* cloudformation:DescribeStackResources
* cloudformation:ExecuteChangeSet
* cloudformation:UpdateStack

The task may also require permissions to upload your application template to the specified Amazon S3 bucket.
2018-08-28T09:48:41.6599502Z ==============================================================================
2018-08-28T09:48:42.2454728Z Configuring credentials for task
2018-08-28T09:48:42.2479981Z ...configuring AWS credentials from task variables
2018-08-28T09:48:42.2497001Z Configuring region for task
2018-08-28T09:48:42.2498107Z ...configured to use region eu-west-1, defined in task variable AWS.Region.
2018-08-28T09:48:42.2579070Z Configuring credentials for task
2018-08-28T09:48:42.2601758Z ...configuring AWS credentials from task variables
2018-08-28T09:48:42.2602776Z Configuring region for task
2018-08-28T09:48:42.2603507Z ...configured to use region eu-west-1, defined in task variable AWS.Region.
2018-08-28T09:48:42.2709231Z Checking existence for stack web-532
2018-08-28T09:48:42.4803631Z Test for existence of stack web-532 returned error: 'ValidationError: Stack with id web-532 does not exist'.
2018-08-28T09:48:42.4803938Z Stack does not exist, switching to create stack mode
2018-08-28T09:48:42.4808980Z Loading template parameters file 'D:\vNext\GenericPool\GPC101\_work\r5\a\_Demo\drop\CFT\web-param.json'
2018-08-28T09:48:42.4815254Z Successfully loaded template parameters
2018-08-28T09:48:42.4815869Z Creating stack with template file undefined
2018-08-28T09:48:42.4817716Z Setting capability CAPABILITY_IAM for stack
2018-08-28T09:48:42.4817955Z Setting capability CAPABILITY_NAMED_IAM for stack
2018-08-28T09:48:43.2407219Z Waiting for stack web-532 to reach create complete status
2018-08-28T09:48:43.2408108Z Setting maximum wait period for stack creation/update to 120 minutes
2018-08-28T10:48:33.8556200Z Stack creation request failed with error: 'Stack web-532 failed to reach completion status, error: 'Resource is not in the state stackCreateComplete'' Error: Stack web-532 failed to reach completion status, error: 'Resource is not in the state stackCreateComplete'
2018-08-28T10:48:33.8556791Z     at .<anonymous> (D:\vNext\GenericPool\GPC101\_work\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.1.3\CloudFormationCreateOrUpdateStack.js:9:22863)
2018-08-28T10:48:33.8557030Z     at throw (native)
2018-08-28T10:48:33.8557281Z     at a (D:\vNext\GenericPool\GPC101\_work\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.1.3\CloudFormationCreateOrUpdateStack.js:9:12425)
2018-08-28T10:48:33.8557556Z     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2018-08-28T10:48:33.8613548Z ##[error]Error: Stack web-532 failed to reach completion status, error: 'Resource is not in the state stackCreateComplete'
2018-08-28T10:48:33.8644907Z ##[section]Finishing: Create/Update Stack: web-532

**Comment by JeffRausch** [comment]
My only thought is to double-check all the timeouts that can be set in the Release pipeline.  There are 3 in this situation (in VSTS, I'm not sure about the TFS install)

1. The CloudFormation call timeout (in the task settings under the "Options" heading) - I assume this is the timeout you are setting...
2. The Task timeout (in the task settings under the "Control Options" heading)
3. The Phase timeout (in the phase settings under the "Execution Plan" heading)

**Comment by steveataws** [comment]
There's no way I know of to break into a task and have it, or some other source, refresh credentials while it's running. Have you considered using a service endpoint configured for assume role credentials? Those credentials would automatically rotate as needed. 

Alternatively you could try using environment variables instead of VSTS variables however I don't see how you'd be able to rotate them while the task is running other than by some external process - and then potentially you get into consistency issues.

**Comment by hunterwerlla** [comment]
Closing because no response

**Comment by convexset** [comment]
Giving CloudFormation a service role (instead of the default session based on the identity of the calling IAM user) should give you more time.
